_target_: robot_io.cams.realsense.realsense.Realsense
_recursive_: false
name: realsenseD435
fps: 30
img_type: "rgb_depth"
resolution: [640, 480] # higher resolution setup
resize_resolution: [640, 360] 
crop_coords: [120, 480, 0, 640]  # crop for longer finger 
# resize_resolution: [640, 480] 
# crop_coords: [0, 480, 0, 640]  # no crop
params:
  white_balance: 3400
  exposure: 230.0
  brightness: 40.0
  contrast: 50.0
  saturation: 64.0
  sharpness: 0.0
  gain: 16.0
  gamma: 220.0
  hue: 0.0
  enable_auto_exposure: 0.0
  enable_auto_white_balance: 0.0
flipped_cam: true # changing this need recalibration
depth_filters: true  # temporal + spatial + hole-fill filters
save_ir: false       # save IR stereo pair to images_ir_left/ and images_ir_right/
